// Code generated by "sumx -type Payment"; DO NOT EDIT.

package main

import "github.com/zkrebbekx/sumx"

// PaymentVariants is the recorded variant set of Payment.
var PaymentVariants = sumx.Define[Payment](
	*new(Card),
	*new(Cash),
	*new(Transfer),
)

// MatchPayment dispatches v to exactly one handler and returns the result.
// Adding or removing a Payment variant changes this signature, so every call
// site must handle every variant — compile-time exhaustiveness.
func MatchPayment[R any](
	v Payment,
	card func(Card) R,
	cash func(Cash) R,
	transfer func(Transfer) R,
) R {
	switch x := v.(type) {
	case Card:
		return card(x)
	case Cash:
		return cash(x)
	case Transfer:
		return transfer(x)
	default:
		panic("sumx: unhandled Payment variant")
	}
}
