package main

import (
	"os"
	"path/filepath"
	"testing"

	. "github.com/smartystreets/goconvey/convey"
)

// writePkg writes named source files into a fresh temp dir and returns it.
func writePkg(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, src := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

const shapeSrc = `package geo

type Shape interface{ sealedShape() }

type Circle struct{ R float64 }
type Rect struct{ W, H float64 }

func (Circle) sealedShape() {}
func (Rect) sealedShape()   {}
`

func TestParsePackage(t *testing.T) {
	Convey("Given a package with a sealed interface and two value variants", t, func() {
		dir := writePkg(t, map[string]string{"shape.go": shapeSrc})

		Convey("When the package is scanned", func() {
			spec, err := parsePackage(dir, "Shape")

			Convey("Then it finds the variants in declaration order", func() {
				So(err, ShouldBeNil)
				So(spec.Package, ShouldEqual, "geo")
				So(spec.Iface, ShouldEqual, "Shape")
				So(len(spec.Variants), ShouldEqual, 2)
				So(spec.Variants[0].Type(), ShouldEqual, "Circle")
				So(spec.Variants[1].Type(), ShouldEqual, "Rect")
			})
		})

		Convey("When a non-existent interface is requested", func() {
			_, err := parsePackage(dir, "Nope")

			Convey("Then it errors", func() {
				So(err, ShouldNotBeNil)
				So(err.Error(), ShouldContainSubstring, "not found")
			})
		})
	})

	Convey("Given variants split across files with a pointer receiver", t, func() {
		dir := writePkg(t, map[string]string{
			"node.go": `package tree
type Node interface{ sealedNode() }
type Leaf struct{ V int }
func (*Leaf) sealedNode() {}
`,
			"branch.go": `package tree
type Branch struct{ L, R Node }
func (*Branch) sealedNode() {}
`,
		})

		Convey("When scanned", func() {
			spec, err := parsePackage(dir, "Node")

			Convey("Then both pointer variants are found, ordered deterministically by filename", func() {
				So(err, ShouldBeNil)
				So(len(spec.Variants), ShouldEqual, 2)
				// branch.go sorts before node.go.
				So(spec.Variants[0].Type(), ShouldEqual, "*Branch")
				So(spec.Variants[1].Type(), ShouldEqual, "*Leaf")
			})
		})
	})

	Convey("Given an interface with no implementers", t, func() {
		dir := writePkg(t, map[string]string{"x.go": `package x
type Empty interface{ sealedEmpty() }
`})
		Convey("When scanned", func() {
			_, err := parsePackage(dir, "Empty")
			Convey("Then it errors that nothing implements it", func() {
				So(err, ShouldNotBeNil)
				So(err.Error(), ShouldContainSubstring, "implement")
			})
		})
	})
}

func TestGenerate(t *testing.T) {
	Convey("Given a parsed Shape spec", t, func() {
		dir := writePkg(t, map[string]string{"shape.go": shapeSrc})
		spec, err := parsePackage(dir, "Shape")
		So(err, ShouldBeNil)

		Convey("When the Match is generated", func() {
			out, err := generate(spec)
			So(err, ShouldBeNil)
			code := string(out)

			Convey("Then it is valid, gofmt'd Go with the DO NOT EDIT header", func() {
				So(code, ShouldStartWith, "// Code generated by")
				So(code, ShouldContainSubstring, "package geo")
			})

			Convey("Then the variant set is defined with *new() values", func() {
				So(code, ShouldContainSubstring, "var ShapeVariants = sumx.Define[Shape](")
				So(code, ShouldContainSubstring, "*new(Circle)")
				So(code, ShouldContainSubstring, "*new(Rect)")
			})

			Convey("Then MatchShape takes one handler per variant", func() {
				So(code, ShouldContainSubstring, "func MatchShape[R any](")
				So(code, ShouldContainSubstring, "circle func(Circle) R")
				So(code, ShouldContainSubstring, "rect func(Rect) R")
			})

			Convey("Then the dispatch switch covers every case", func() {
				So(code, ShouldContainSubstring, "case Circle:")
				So(code, ShouldContainSubstring, "case Rect:")
			})
		})
	})
}

func TestHandlerNameAvoidsKeyword(t *testing.T) {
	Convey("Given a variant whose lowercased name is a Go keyword", t, func() {
		dir := writePkg(t, map[string]string{"tok.go": `package lex
type Token interface{ sealedToken() }
type Range struct{ Lo, Hi int }
type Ident struct{ Name string }
func (Range) sealedToken() {}
func (Ident) sealedToken() {}
`})
		spec, err := parsePackage(dir, "Token")
		So(err, ShouldBeNil)

		Convey("When generated", func() {
			out, err := generate(spec)
			So(err, ShouldBeNil)
			code := string(out)

			Convey("Then the handler parameter is suffixed to stay valid", func() {
				So(code, ShouldContainSubstring, "range_ func(Range) R")
				So(code, ShouldContainSubstring, "ident func(Ident) R")
			})
		})
	})
}
